#include "Plant.h"
#include <iostream>

/**
 * @brief Constructs a Plant with the specified capacity, type, and location.
 *
 * Initializes occupancy to 0 and reduces resource levels based on the plant type.
 * 
 * @param capacity The capacity of the plant.
 * @param type The type of plant.
 * @param location The location of the plant.
 */
Plant::Plant(int capacity, std::string type, std::string location) : Industrial(capacity, location)
{
    this->type = type;
    this->capacity = capacity;
    this->location = location;
    this->occupancy = 0;

    if (type == "Power") 
    {
        ResourceManager::instance()->decreaseResourceLevels(0, 10, 5, 10, 3);
    } 
    else if (type == "Water") 
    {
        ResourceManager::instance()->decreaseResourceLevels(10, 0, 4, 6, 2);
    } 
    else if (type == "Materials") 
    {
        ResourceManager::instance()->decreaseResourceLevels(5, 5, 3, 5, 4);
    }
}

/**
 * @brief Constructs a PowerPlant with the specified capacity and location.
 * 
 * Outputs a message indicating creation details.
 * 
 * @param capacity The capacity of the Power Plant.
 * @param location The location of the Power Plant.
 */
PowerPlant::PowerPlant(int capacity, std::string location) : Plant(capacity, "Power", location) 
{
    std::cout << "A Power factory has been created at " << location
              << " with a max capacity of " << capacity << std::endl;
}

/**
 * @brief Constructs a WaterPlant with the specified capacity and location.
 * 
 * Outputs a message indicating creation details.
 * 
 * @param capacity The capacity of the Water Plant.
 * @param location The location of the Water Plant.
 */
WaterPlant::WaterPlant(int capacity, std::string location) : Plant(capacity, "Water", location)
{
    std::cout << "A Water factory has been created at " << location
              << " with a max capacity of " << capacity << std::endl;
}

/**
 * @brief Constructs a MaterialsPlant with the specified capacity and location.
 * 
 * Outputs a message indicating creation details.
 * 
 * @param capacity The capacity of the Materials Plant.
 * @param location The location of the Materials Plant.
 */
MaterialsPlant::MaterialsPlant(int capacity, std::string location) : Plant(capacity, "Materials", location)
{
    std::cout << "A Materials factory has been created at " << location
              << " with a max capacity of " << capacity << std::endl;
}

/**
 * @brief Generates additional water resources for the WaterPlant.
 */
void WaterPlant::generate()
{
    std::cout << "More water has been generated by the Water Plant" << std::endl;
}

/**
 * @brief Generates additional power resources for the PowerPlant.
 */
void PowerPlant::generate()
{
    std::cout << "More power has been generated by the Power Plant" << std::endl;
}

/**
 * @brief Generates additional materials resources for the MaterialsPlant.
 */
void MaterialsPlant::generate()
{
    std::cout << "More materials have been generated by the Materials Plant" << std::endl;
}

/**
 * @brief Builds and returns a new WaterPlant.
 * 
 * @return Pointer to a new WaterPlant object.
 */
Building* WaterPlant::build()
{
    return new WaterPlant(capacity, location);
}

/**
 * @brief Builds and returns a new PowerPlant.
 * 
 * @return Pointer to a new PowerPlant object.
 */
Building* PowerPlant::build()
{
    return new PowerPlant(capacity, location);
}

/**
 * @brief Builds and returns a new MaterialsPlant.
 * 
 * @return Pointer to a new MaterialsPlant object.
 */
Building* MaterialsPlant::build()
{
    return new MaterialsPlant(capacity, location);
}
